package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ASSET.
 */
public class Asset {

    private Long asset_id;
    private String asset_code;
    private Long company_id;
    private Long department_id;
    private Long category_id;
    private Long sub_category_id;
    private Long warehouse_id;
    private String seri;
    private String warehouse_seri;
    private String user_using;
    private String name;
    private Integer f_active;
    private String created_at;
    private String updated_at;
    private String department_name;
    private Long session_id;
    private Integer status;

    public Asset() {
    }

    public Asset(Long asset_id) {
        this.asset_id = asset_id;
    }

    public Asset(Long asset_id, String asset_code, Long company_id, Long department_id, Long category_id, Long sub_category_id, Long warehouse_id, String seri, String warehouse_seri, String user_using, String name, Integer f_active, String created_at, String updated_at, String department_name, Long session_id, Integer status) {
        this.asset_id = asset_id;
        this.asset_code = asset_code;
        this.company_id = company_id;
        this.department_id = department_id;
        this.category_id = category_id;
        this.sub_category_id = sub_category_id;
        this.warehouse_id = warehouse_id;
        this.seri = seri;
        this.warehouse_seri = warehouse_seri;
        this.user_using = user_using;
        this.name = name;
        this.f_active = f_active;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.department_name = department_name;
        this.session_id = session_id;
        this.status = status;
    }

    public Long getAsset_id() {
        return asset_id;
    }

    public void setAsset_id(Long asset_id) {
        this.asset_id = asset_id;
    }

    public String getAsset_code() {
        return asset_code;
    }

    public void setAsset_code(String asset_code) {
        this.asset_code = asset_code;
    }

    public Long getCompany_id() {
        return company_id;
    }

    public void setCompany_id(Long company_id) {
        this.company_id = company_id;
    }

    public Long getDepartment_id() {
        return department_id;
    }

    public void setDepartment_id(Long department_id) {
        this.department_id = department_id;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public Long getSub_category_id() {
        return sub_category_id;
    }

    public void setSub_category_id(Long sub_category_id) {
        this.sub_category_id = sub_category_id;
    }

    public Long getWarehouse_id() {
        return warehouse_id;
    }

    public void setWarehouse_id(Long warehouse_id) {
        this.warehouse_id = warehouse_id;
    }

    public String getSeri() {
        return seri;
    }

    public void setSeri(String seri) {
        this.seri = seri;
    }

    public String getWarehouse_seri() {
        return warehouse_seri;
    }

    public void setWarehouse_seri(String warehouse_seri) {
        this.warehouse_seri = warehouse_seri;
    }

    public String getUser_using() {
        return user_using;
    }

    public void setUser_using(String user_using) {
        this.user_using = user_using;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getF_active() {
        return f_active;
    }

    public void setF_active(Integer f_active) {
        this.f_active = f_active;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public String getDepartment_name() {
        return department_name;
    }

    public void setDepartment_name(String department_name) {
        this.department_name = department_name;
    }

    public Long getSession_id() {
        return session_id;
    }

    public void setSession_id(Long session_id) {
        this.session_id = session_id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
