package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.User;
import greendao.Session;
import greendao.Asset;
import greendao.Category;
import greendao.SubCategory;
import greendao.Department;
import greendao.Warehouse;

import greendao.UserDao;
import greendao.SessionDao;
import greendao.AssetDao;
import greendao.CategoryDao;
import greendao.SubCategoryDao;
import greendao.DepartmentDao;
import greendao.WarehouseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig sessionDaoConfig;
    private final DaoConfig assetDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig subCategoryDaoConfig;
    private final DaoConfig departmentDaoConfig;
    private final DaoConfig warehouseDaoConfig;

    private final UserDao userDao;
    private final SessionDao sessionDao;
    private final AssetDao assetDao;
    private final CategoryDao categoryDao;
    private final SubCategoryDao subCategoryDao;
    private final DepartmentDao departmentDao;
    private final WarehouseDao warehouseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        assetDaoConfig = daoConfigMap.get(AssetDao.class).clone();
        assetDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        subCategoryDaoConfig = daoConfigMap.get(SubCategoryDao.class).clone();
        subCategoryDaoConfig.initIdentityScope(type);

        departmentDaoConfig = daoConfigMap.get(DepartmentDao.class).clone();
        departmentDaoConfig.initIdentityScope(type);

        warehouseDaoConfig = daoConfigMap.get(WarehouseDao.class).clone();
        warehouseDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);
        assetDao = new AssetDao(assetDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        subCategoryDao = new SubCategoryDao(subCategoryDaoConfig, this);
        departmentDao = new DepartmentDao(departmentDaoConfig, this);
        warehouseDao = new WarehouseDao(warehouseDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Session.class, sessionDao);
        registerDao(Asset.class, assetDao);
        registerDao(Category.class, categoryDao);
        registerDao(SubCategory.class, subCategoryDao);
        registerDao(Department.class, departmentDao);
        registerDao(Warehouse.class, warehouseDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        sessionDaoConfig.getIdentityScope().clear();
        assetDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        subCategoryDaoConfig.getIdentityScope().clear();
        departmentDaoConfig.getIdentityScope().clear();
        warehouseDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public AssetDao getAssetDao() {
        return assetDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public SubCategoryDao getSubCategoryDao() {
        return subCategoryDao;
    }

    public DepartmentDao getDepartmentDao() {
        return departmentDao;
    }

    public WarehouseDao getWarehouseDao() {
        return warehouseDao;
    }

}
