package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEPARTMENT.
 */
public class Department {

    private Long department_id;
    private String department_code;
    private String department_name;
    private String description;

    public Department() {
    }

    public Department(Long department_id) {
        this.department_id = department_id;
    }

    public Department(Long department_id, String department_code, String department_name, String description) {
        this.department_id = department_id;
        this.department_code = department_code;
        this.department_name = department_name;
        this.description = description;
    }

    public Long getDepartment_id() {
        return department_id;
    }

    public void setDepartment_id(Long department_id) {
        this.department_id = department_id;
    }

    public String getDepartment_code() {
        return department_code;
    }

    public void setDepartment_code(String department_code) {
        this.department_code = department_code;
    }

    public String getDepartment_name() {
        return department_name;
    }

    public void setDepartment_name(String department_name) {
        this.department_name = department_name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
