package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SESSION.
 */
public class Session {

    private Long session_id;
    private Long account_id;
    private Long company_id;
    private String name;
    private String description;
    private String session_date;
    private String created_at;
    private String updated_at;
    private Integer is_chosen;

    public Session() {
    }

    public Session(Long session_id) {
        this.session_id = session_id;
    }

    public Session(Long session_id, Long account_id, Long company_id, String name, String description, String session_date, String created_at, String updated_at, Integer is_chosen) {
        this.session_id = session_id;
        this.account_id = account_id;
        this.company_id = company_id;
        this.name = name;
        this.description = description;
        this.session_date = session_date;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.is_chosen = is_chosen;
    }

    public Long getSession_id() {
        return session_id;
    }

    public void setSession_id(Long session_id) {
        this.session_id = session_id;
    }

    public Long getAccount_id() {
        return account_id;
    }

    public void setAccount_id(Long account_id) {
        this.account_id = account_id;
    }

    public Long getCompany_id() {
        return company_id;
    }

    public void setCompany_id(Long company_id) {
        this.company_id = company_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSession_date() {
        return session_date;
    }

    public void setSession_date(String session_date) {
        this.session_date = session_date;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public Integer getIs_chosen() {
        return is_chosen;
    }

    public void setIs_chosen(Integer is_chosen) {
        this.is_chosen = is_chosen;
    }

}
