package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUB_CATEGORY.
 */
public class SubCategory {

    private Long sub_category_id;
    private Long category_id;
    private String sub_category_name;

    public SubCategory() {
    }

    public SubCategory(Long sub_category_id) {
        this.sub_category_id = sub_category_id;
    }

    public SubCategory(Long sub_category_id, Long category_id, String sub_category_name) {
        this.sub_category_id = sub_category_id;
        this.category_id = category_id;
        this.sub_category_name = sub_category_name;
    }

    public Long getSub_category_id() {
        return sub_category_id;
    }

    public void setSub_category_id(Long sub_category_id) {
        this.sub_category_id = sub_category_id;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public String getSub_category_name() {
        return sub_category_name;
    }

    public void setSub_category_name(String sub_category_name) {
        this.sub_category_name = sub_category_name;
    }

}
